/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import AppPackage.AnimationClass;
import Controlador.Conexion;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import Formulariospanel.CambiaPanel;
import java.sql.ResultSet;
import java.sql.SQLException;
import mdlaf.MaterialLookAndFeel;
import principal.Login;

/**
 *
 * @author RojeruSan
 */
public class Principal123 extends javax.swing.JFrame {

    int x, y;

    /**
     * Creates new form Principal
     */
    public Principal123() {
        initComponents();
        Login close = new Login();
        close.setVisible(false);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        this.uno.setSelected(true);

        new CambiaPanel(pnlPrincipal,
                new Formulariospanel.pnlHome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        uno = new rsbuttom.RSButtonMetro();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tres = new rsbuttom.RSButtonMetro();
        dos = new rsbuttom.RSButtonMetro();
        cinco = new rsbuttom.RSButtonMetro();
        ocho = new rsbuttom.RSButtonMetro();
        siete = new rsbuttom.RSButtonMetro();
        seis = new rsbuttom.RSButtonMetro();
        cuatro = new rsbuttom.RSButtonMetro();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Cerrarsesion = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        pnlMenu1 = new javax.swing.JPanel();
        uno1 = new rsbuttom.RSButtonMetro();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tres1 = new rsbuttom.RSButtonMetro();
        dos1 = new rsbuttom.RSButtonMetro();
        cinco1 = new rsbuttom.RSButtonMetro();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ocho1 = new rsbuttom.RSButtonMetro();
        siete1 = new rsbuttom.RSButtonMetro();
        seis1 = new rsbuttom.RSButtonMetro();
        cuatro1 = new rsbuttom.RSButtonMetro();
        volver = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(140, 102, 53));

        jPanel1.setBackground(new java.awt.Color(140, 102, 53));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        pnlMenu.setBackground(new java.awt.Color(140, 102, 53));
        pnlMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uno.setForeground(new java.awt.Color(128, 128, 131));
        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sin título-4.png"))); // NOI18N
        uno.setText("Inicio");
        uno.setColorHover(new java.awt.Color(99, 59, 30));
        uno.setColorNormal(new java.awt.Color(91, 55, 21));
        uno.setColorPressed(new java.awt.Color(99, 59, 30));
        uno.setColorTextNormal(new java.awt.Color(128, 128, 131));
        uno.setColorTextPressed(new java.awt.Color(128, 128, 131));
        uno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uno.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        uno.setIconTextGap(25);
        uno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                unoMousePressed(evt);
            }
        });
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        pnlMenu.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 86, 230, 50));

        jPanel4.setBackground(new java.awt.Color(140, 102, 53));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formularios");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlMenu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 270, 80));

        tres.setForeground(new java.awt.Color(128, 128, 131));
        tres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/images (1).png"))); // NOI18N
        tres.setText("Población");
        tres.setToolTipText("");
        tres.setColorHover(new java.awt.Color(99, 59, 30));
        tres.setColorNormal(new java.awt.Color(91, 55, 21));
        tres.setColorPressed(new java.awt.Color(99, 59, 30));
        tres.setColorTextNormal(new java.awt.Color(128, 128, 131));
        tres.setColorTextPressed(new java.awt.Color(128, 128, 131));
        tres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tres.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tres.setIconTextGap(19);
        tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tresMousePressed(evt);
            }
        });
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        pnlMenu.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 186, 230, 50));

        dos.setForeground(new java.awt.Color(128, 128, 131));
        dos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pasto.png"))); // NOI18N
        dos.setText("Potrero");
        dos.setColorHover(new java.awt.Color(99, 59, 30));
        dos.setColorNormal(new java.awt.Color(91, 55, 21));
        dos.setColorPressed(new java.awt.Color(99, 59, 30));
        dos.setColorTextNormal(new java.awt.Color(128, 128, 131));
        dos.setColorTextPressed(new java.awt.Color(128, 128, 131));
        dos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        dos.setIconTextGap(25);
        dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dosMousePressed(evt);
            }
        });
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });
        pnlMenu.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 136, 230, 50));

        cinco.setForeground(new java.awt.Color(128, 128, 131));
        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/market.png"))); // NOI18N
        cinco.setText("Vacio");
        cinco.setColorHover(new java.awt.Color(99, 59, 30));
        cinco.setColorNormal(new java.awt.Color(91, 55, 21));
        cinco.setColorPressed(new java.awt.Color(99, 59, 30));
        cinco.setColorTextNormal(new java.awt.Color(128, 128, 131));
        cinco.setColorTextPressed(new java.awt.Color(128, 128, 131));
        cinco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cinco.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cinco.setIconTextGap(19);
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cincoMousePressed(evt);
            }
        });
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        pnlMenu.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 286, 230, 50));

        ocho.setForeground(new java.awt.Color(128, 128, 131));
        ocho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        ocho.setText("Vacio");
        ocho.setColorHover(new java.awt.Color(99, 59, 30));
        ocho.setColorNormal(new java.awt.Color(91, 55, 21));
        ocho.setColorPressed(new java.awt.Color(99, 59, 30));
        ocho.setColorTextNormal(new java.awt.Color(128, 128, 131));
        ocho.setColorTextPressed(new java.awt.Color(128, 128, 131));
        ocho.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ocho.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ocho.setIconTextGap(19);
        ocho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ochoMousePressed(evt);
            }
        });
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });
        pnlMenu.add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 490, 230, 50));

        siete.setForeground(new java.awt.Color(128, 128, 131));
        siete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ios.png"))); // NOI18N
        siete.setText("Vacio");
        siete.setColorHover(new java.awt.Color(99, 59, 30));
        siete.setColorNormal(new java.awt.Color(91, 55, 21));
        siete.setColorPressed(new java.awt.Color(99, 59, 30));
        siete.setColorTextNormal(new java.awt.Color(128, 128, 131));
        siete.setColorTextPressed(new java.awt.Color(128, 128, 131));
        siete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        siete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        siete.setIconTextGap(19);
        siete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sieteMousePressed(evt);
            }
        });
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });
        pnlMenu.add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 440, 230, 50));

        seis.setForeground(new java.awt.Color(128, 128, 131));
        seis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/android.png"))); // NOI18N
        seis.setText("Vacio");
        seis.setColorHover(new java.awt.Color(99, 59, 30));
        seis.setColorNormal(new java.awt.Color(91, 55, 21));
        seis.setColorPressed(new java.awt.Color(99, 59, 30));
        seis.setColorTextNormal(new java.awt.Color(128, 128, 131));
        seis.setColorTextPressed(new java.awt.Color(128, 128, 131));
        seis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seis.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        seis.setIconTextGap(25);
        seis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seisMousePressed(evt);
            }
        });
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        pnlMenu.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 390, 230, 50));

        cuatro.setForeground(new java.awt.Color(128, 128, 131));
        cuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/feeedback.png"))); // NOI18N
        cuatro.setText("Vacio");
        cuatro.setColorHover(new java.awt.Color(99, 59, 30));
        cuatro.setColorNormal(new java.awt.Color(91, 55, 21));
        cuatro.setColorPressed(new java.awt.Color(99, 59, 30));
        cuatro.setColorTextNormal(new java.awt.Color(128, 128, 131));
        cuatro.setColorTextPressed(new java.awt.Color(128, 128, 131));
        cuatro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cuatro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cuatro.setIconTextGap(19);
        cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuatroMousePressed(evt);
            }
        });
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });
        pnlMenu.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 236, 230, 50));

        jPanel5.setBackground(new java.awt.Color(140, 102, 53));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMenu.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 260, 60));

        jPanel9.setBackground(new java.awt.Color(140, 102, 53));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Reportes");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        pnlMenu.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 330, 258, -1));

        jLabel7.setBackground(new java.awt.Color(140, 102, 53));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/para fondo.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        pnlMenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 10, 500));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 8.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pnlMenu, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(91, 55, 21));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jButton1.setToolTipText("Menu");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        Cerrarsesion.setBackground(new java.awt.Color(255, 255, 255));
        Cerrarsesion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cerrarsesion.setForeground(new java.awt.Color(255, 255, 255));
        Cerrarsesion.setText("Cerrar sesión");
        Cerrarsesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarsesionMouseClicked(evt);
            }
        });
        jPanel2.add(Cerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 10, 140, 20));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(114, 76, 33));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Visualizador");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(609, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(pnlCentro, gridBagConstraints);

        pnlMenu1.setBackground(new java.awt.Color(140, 102, 53));
        pnlMenu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMenu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uno1.setForeground(new java.awt.Color(128, 128, 131));
        uno1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        uno1.setText("Raza");
        uno1.setColorHover(new java.awt.Color(99, 59, 30));
        uno1.setColorNormal(new java.awt.Color(91, 55, 21));
        uno1.setColorPressed(new java.awt.Color(99, 59, 30));
        uno1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        uno1.setColorTextPressed(new java.awt.Color(128, 128, 131));
        uno1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uno1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        uno1.setIconTextGap(25);
        uno1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                uno1MousePressed(evt);
            }
        });
        uno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uno1ActionPerformed(evt);
            }
        });
        pnlMenu1.add(uno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 86, 230, 50));

        jPanel7.setBackground(new java.awt.Color(140, 102, 53));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(128, 128, 131));
        jLabel5.setText("PEOPLE");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        pnlMenu1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 270, 60));

        tres1.setForeground(new java.awt.Color(128, 128, 131));
        tres1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/iconvaca.png"))); // NOI18N
        tres1.setText("Vaca");
        tres1.setColorHover(new java.awt.Color(99, 59, 30));
        tres1.setColorNormal(new java.awt.Color(91, 55, 21));
        tres1.setColorPressed(new java.awt.Color(99, 59, 30));
        tres1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        tres1.setColorTextPressed(new java.awt.Color(128, 128, 131));
        tres1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tres1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tres1.setIconTextGap(19);
        tres1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tres1MousePressed(evt);
            }
        });
        tres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tres1ActionPerformed(evt);
            }
        });
        pnlMenu1.add(tres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 186, 230, 50));

        dos1.setForeground(new java.awt.Color(128, 128, 131));
        dos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/feeeee.png"))); // NOI18N
        dos1.setText("Toro");
        dos1.setColorHover(new java.awt.Color(99, 59, 30));
        dos1.setColorNormal(new java.awt.Color(91, 55, 21));
        dos1.setColorPressed(new java.awt.Color(99, 59, 30));
        dos1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        dos1.setColorTextPressed(new java.awt.Color(128, 128, 131));
        dos1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dos1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        dos1.setIconTextGap(25);
        dos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dos1MousePressed(evt);
            }
        });
        dos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dos1ActionPerformed(evt);
            }
        });
        pnlMenu1.add(dos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 136, 230, 50));

        cinco1.setForeground(new java.awt.Color(128, 128, 131));
        cinco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/market.png"))); // NOI18N
        cinco1.setText("vacio");
        cinco1.setColorHover(new java.awt.Color(99, 59, 30));
        cinco1.setColorNormal(new java.awt.Color(91, 55, 21));
        cinco1.setColorPressed(new java.awt.Color(99, 59, 30));
        cinco1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        cinco1.setColorTextPressed(new java.awt.Color(128, 128, 131));
        cinco1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cinco1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cinco1.setIconTextGap(19);
        cinco1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cinco1MousePressed(evt);
            }
        });
        cinco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinco1ActionPerformed(evt);
            }
        });
        pnlMenu1.add(cinco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 286, 230, 50));

        jPanel8.setBackground(new java.awt.Color(140, 102, 53));
        jPanel8.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(128, 128, 131));
        jLabel6.setText("DEVICE");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pnlMenu1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 330, 258, -1));

        ocho1.setForeground(new java.awt.Color(128, 128, 131));
        ocho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        ocho1.setText("vacio");
        ocho1.setColorHover(new java.awt.Color(99, 59, 30));
        ocho1.setColorNormal(new java.awt.Color(91, 55, 21));
        ocho1.setColorPressed(new java.awt.Color(99, 59, 30));
        ocho1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        ocho1.setColorTextPressed(new java.awt.Color(128, 128, 131));
        ocho1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ocho1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ocho1.setIconTextGap(19);
        ocho1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ocho1MousePressed(evt);
            }
        });
        ocho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocho1ActionPerformed(evt);
            }
        });
        pnlMenu1.add(ocho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 490, 230, 50));

        siete1.setForeground(new java.awt.Color(128, 128, 131));
        siete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ios.png"))); // NOI18N
        siete1.setText("vacio");
        siete1.setColorHover(new java.awt.Color(99, 59, 30));
        siete1.setColorNormal(new java.awt.Color(91, 55, 21));
        siete1.setColorPressed(new java.awt.Color(99, 59, 30));
        siete1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        siete1.setColorTextPressed(new java.awt.Color(128, 128, 131));
        siete1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        siete1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        siete1.setIconTextGap(19);
        siete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                siete1MousePressed(evt);
            }
        });
        siete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siete1ActionPerformed(evt);
            }
        });
        pnlMenu1.add(siete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 440, 230, 50));

        seis1.setForeground(new java.awt.Color(128, 128, 131));
        seis1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/android.png"))); // NOI18N
        seis1.setText("vacio");
        seis1.setColorHover(new java.awt.Color(99, 59, 30));
        seis1.setColorNormal(new java.awt.Color(91, 55, 21));
        seis1.setColorPressed(new java.awt.Color(99, 59, 30));
        seis1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        seis1.setColorTextPressed(new java.awt.Color(128, 128, 131));
        seis1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seis1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        seis1.setIconTextGap(25);
        seis1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seis1MousePressed(evt);
            }
        });
        seis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seis1ActionPerformed(evt);
            }
        });
        pnlMenu1.add(seis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 390, 230, 50));

        cuatro1.setForeground(new java.awt.Color(128, 128, 131));
        cuatro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ternero.png"))); // NOI18N
        cuatro1.setText("Cría");
        cuatro1.setColorHover(new java.awt.Color(99, 59, 30));
        cuatro1.setColorNormal(new java.awt.Color(91, 55, 21));
        cuatro1.setColorPressed(new java.awt.Color(99, 59, 30));
        cuatro1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        cuatro1.setColorTextPressed(new java.awt.Color(128, 128, 131));
        cuatro1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cuatro1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cuatro1.setIconTextGap(19);
        cuatro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuatro1MousePressed(evt);
            }
        });
        cuatro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatro1ActionPerformed(evt);
            }
        });
        pnlMenu1.add(cuatro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 236, 230, 50));

        volver.setBackground(new java.awt.Color(239, 238, 244));
        volver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver-con-flecha-en-boton-cuadrado-solido.png"))); // NOI18N
        volver.setText("Volver");
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
        });
        pnlMenu1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 557, 90, -1));

        jPanel10.setBackground(new java.awt.Color(140, 102, 53));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnlMenu1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 110, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(128, 128, 131));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/para fondo.jpg"))); // NOI18N
        pnlMenu1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 10, 90));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(128, 128, 131));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/para fondo.jpg"))); // NOI18N
        pnlMenu1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 610));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 8.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pnlMenu1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        new CambiaPanel(pnlPrincipal, new Formulariospanel.pnlHome());
        if (this.uno.isSelected()) {
            this.uno.setColorNormal(new Color(91, 55, 21));
            this.uno.setColorHover(new Color(99, 59, 30)); 
            this.uno.setColorPressed(new Color(99, 59, 30));

            this.dos.setColorNormal(new Color(91, 55, 21));
            this.dos.setColorHover(new Color(99, 59, 30));
            this.dos.setColorPressed(new Color(99, 59, 30));

            this.tres.setColorNormal(new Color(91, 55, 21));
            this.tres.setColorHover(new Color(99, 59, 30));
            this.tres.setColorPressed(new Color(99, 59, 30));

            this.cuatro.setColorNormal(new Color(91, 55, 21));
            this.cuatro.setColorHover(new Color(99, 59, 30));
            this.cuatro.setColorPressed(new Color(99, 59, 30));

            this.cinco.setColorNormal(new Color(91, 55, 21));
            this.cinco.setColorHover(new Color(99, 59, 30));
            this.cinco.setColorPressed(new Color(99, 59, 30));

            this.seis.setColorNormal(new Color(91, 55, 21));
            this.seis.setColorHover(new Color(99, 59, 30));
            this.seis.setColorPressed(new Color(99, 59, 30));

            this.siete.setColorNormal(new Color(91, 55, 21));
            this.siete.setColorHover(new Color(99, 59, 30));
            this.siete.setColorPressed(new Color(99, 59, 30));

            this.ocho.setColorNormal(new Color(91, 55, 21));
            this.ocho.setColorHover(new Color(99, 59, 30));
            this.ocho.setColorPressed(new Color(99, 59, 30));
        } else {
            this.uno.setColorNormal(new Color(91, 55, 21));
            this.uno.setColorHover(new Color(99, 59, 30));
            this.uno.setColorPressed(new Color(99, 59, 30));
        }
    }//GEN-LAST:event_unoActionPerformed

    private void unoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unoMousePressed
        this.uno.setSelected(true);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_unoMousePressed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
//        new CambiaPanel(pnlPrincipal, new Formulariospanel.pnlChat());
        if (this.tres.isSelected()) {
            this.tres.setColorNormal(new Color(91, 55, 21));
            this.tres.setColorHover(new Color(99, 59, 30));
            this.tres.setColorPressed(new Color(99, 59, 30));

            this.uno.setColorNormal(new Color(91, 55, 21));
            this.uno.setColorHover(new Color(99, 59, 30));
            this.uno.setColorPressed(new Color(99, 59, 30));

            this.dos.setColorNormal(new Color(91, 55, 21));
            this.dos.setColorHover(new Color(99, 59, 30));
            this.dos.setColorPressed(new Color(99, 59, 30));

            this.cuatro.setColorNormal(new Color(91, 55, 21));
            this.cuatro.setColorHover(new Color(99, 59, 30));
            this.cuatro.setColorPressed(new Color(99, 59, 30));

            this.cinco.setColorNormal(new Color(91, 55, 21));
            this.cinco.setColorHover(new Color(99, 59, 30));
            this.cinco.setColorPressed(new Color(99, 59, 30));

            this.seis.setColorNormal(new Color(91, 55, 21));
            this.seis.setColorHover(new Color(99, 59, 30));
            this.seis.setColorPressed(new Color(99, 59, 30));

            this.siete.setColorNormal(new Color(91, 55, 21));
            this.siete.setColorHover(new Color(99, 59, 30));
            this.siete.setColorPressed(new Color(99, 59, 30));

            this.ocho.setColorNormal(new Color(91, 55, 21));
            this.ocho.setColorHover(new Color(99, 59, 30));
            this.ocho.setColorPressed(new Color(99, 59, 30));
        } else {
            this.tres.setColorNormal(new Color(239, 238, 244));
            this.tres.setColorHover(new Color(204, 204, 204));
            this.tres.setColorPressed(new Color(204, 204, 204));
        }
        if (this.tres.isSelected()) {
            pnlMenu.setVisible(false);
            pnlMenu1.setVisible(true);
            uno1.setVisible(true);
            dos1.setVisible(true);
        }


    }//GEN-LAST:event_tresActionPerformed

    private void tresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresMousePressed
        if (this.tres.isSelected()) {
            pnlMenu.setVisible(false);
            pnlMenu1.setVisible(true);
            uno1.setVisible(true);
            dos1.setVisible(true);

//            pnlMenu.setVisible(true);
        } else {
            this.uno.setSelected(false);
            this.dos.setSelected(false);
            this.tres.setSelected(true);
            this.cuatro.setSelected(false);
            this.cinco.setSelected(false);
            this.seis.setSelected(false);
            this.siete.setSelected(false);
            this.ocho.setSelected(false);
        }


    }//GEN-LAST:event_tresMousePressed

    private void dosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosMousePressed

        this.uno.setSelected(false);
        this.dos.setSelected(true);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_dosMousePressed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        new CambiaPanel(pnlPrincipal, new Formulariospanel.pnlpotrero());
        if (this.dos.isSelected()) {
            this.dos.setColorNormal(new Color(91, 55, 21));
            this.dos.setColorHover(new Color(99, 59, 30));
            this.dos.setColorPressed(new Color(99, 59, 30));

            this.uno.setColorNormal(new Color(91, 55, 21));
            this.uno.setColorHover(new Color(99, 59, 30));
            this.uno.setColorPressed(new Color(99, 59, 30));

            this.tres.setColorNormal(new Color(91, 55, 21));
            this.tres.setColorHover(new Color(99, 59, 30));
            this.tres.setColorPressed(new Color(99, 59, 30));

            this.cuatro.setColorNormal(new Color(91, 55, 21));
            this.cuatro.setColorHover(new Color(99, 59, 30));
            this.cuatro.setColorPressed(new Color(99, 59, 30));

            this.cinco.setColorNormal(new Color(91, 55, 21));
            this.cinco.setColorHover(new Color(99, 59, 30));
            this.cinco.setColorPressed(new Color(99, 59, 30));

            this.seis.setColorNormal(new Color(91, 55, 21));
            this.seis.setColorHover(new Color(99, 59, 30));
            this.seis.setColorPressed(new Color(99, 59, 30));

            this.siete.setColorNormal(new Color(91, 55, 21));
            this.siete.setColorHover(new Color(99, 59, 30));
            this.siete.setColorPressed(new Color(99, 59, 30));

            this.ocho.setColorNormal(new Color(91, 55, 21));
            this.ocho.setColorHover(new Color(99, 59, 30));
            this.ocho.setColorPressed(new Color(99, 59, 30));
        } else {
            this.dos.setColorNormal(new Color(91, 55, 21));
            this.dos.setColorHover(new Color(99, 59, 30));
            this.dos.setColorPressed(new Color(99, 59, 30));
        }
    }//GEN-LAST:event_dosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int posicion = Cerrarsesion.getX();
        if (posicion > -1) {
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, Cerrarsesion);
        } else {
            Animacion.Animacion.mover_derecha(-264, 59, 2, 2, Cerrarsesion);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void ochoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ochoMousePressed
//        if (this.ocho.isSelected()) {
//            pnlMenu.setVisible(false);
//            pnlMenu1.setVisible(true);
//            uno1.setVisible(true);
//            dos1.setVisible(true);
//
////            pnlMenu.setVisible(true);
//        } else {
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(true);
//        }


    }//GEN-LAST:event_ochoMousePressed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
//        new CambiaPanel(pnlPrincipal, new paneles.pnlWeb());
        if (this.ocho.isSelected()) {
            this.uno.setColorNormal(new Color(91, 55, 21));
            this.uno.setColorHover(new Color(99, 59, 30));
            this.uno.setColorPressed(new Color(99, 59, 30));

            this.dos.setColorNormal(new Color(91, 55, 21));
            this.dos.setColorHover(new Color(99, 59, 30));
            this.dos.setColorPressed(new Color(99, 59, 30));

            this.tres.setColorNormal(new Color(91, 55, 21));
            this.tres.setColorHover(new Color(99, 59, 30));
            this.tres.setColorPressed(new Color(99, 59, 30));

            this.cuatro.setColorNormal(new Color(91, 55, 21));
            this.cuatro.setColorHover(new Color(99, 59, 30));
            this.cuatro.setColorPressed(new Color(99, 59, 30));

            this.cinco.setColorNormal(new Color(91, 55, 21));
            this.cinco.setColorHover(new Color(99, 59, 30));
            this.cinco.setColorPressed(new Color(99, 59, 30));

            this.seis.setColorNormal(new Color(91, 55, 21));
            this.seis.setColorHover(new Color(99, 59, 30));
            this.seis.setColorPressed(new Color(99, 59, 30));

            this.siete.setColorNormal(new Color(91, 55, 21));
            this.siete.setColorHover(new Color(99, 59, 30));
            this.siete.setColorPressed(new Color(99, 59, 30));

            this.ocho.setColorNormal(new Color(91, 55, 21));
            this.ocho.setColorHover(new Color(99, 59, 30));
            this.ocho.setColorPressed(new Color(99, 59, 30));
        } else {
            this.ocho.setColorNormal(new Color(91, 55, 21));
            this.ocho.setColorHover(new Color(99, 59, 30));
            this.ocho.setColorPressed(new Color(99, 59, 30));
        }

//        if (this.ocho.isSelected()) {
//            pnlMenu.setVisible(false);
//            pnlMenu1.setVisible(true);
//            uno1.setVisible(true);
//            dos1.setVisible(true);
////            pnlMenu.setVisible(true);
//
//        } else {
//            JOptionPane.showMessageDialog(null, "error");
//        }

    }//GEN-LAST:event_ochoActionPerformed

    private void sieteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sieteMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
        this.siete.setSelected(true);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_sieteMousePressed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
//        new CambiaPanel(pnlPrincipal, new paneles.pnlIOS());
        if (this.siete.isSelected()) {
            this.uno.setColorNormal(new Color(91, 55, 21));
            this.uno.setColorHover(new Color(99, 59, 30));
            this.uno.setColorPressed(new Color(99, 59, 30));

            this.dos.setColorNormal(new Color(91, 55, 21));
            this.dos.setColorHover(new Color(99, 59, 30));
            this.dos.setColorPressed(new Color(99, 59, 30));

            this.tres.setColorNormal(new Color(91, 55, 21));
            this.tres.setColorHover(new Color(99, 59, 30));
            this.tres.setColorPressed(new Color(99, 59, 30));

            this.cuatro.setColorNormal(new Color(91, 55, 21));
            this.cuatro.setColorHover(new Color(99, 59, 30));
            this.cuatro.setColorPressed(new Color(99, 59, 30));

            this.cinco.setColorNormal(new Color(91, 55, 21));
            this.cinco.setColorHover(new Color(99, 59, 30));
            this.cinco.setColorPressed(new Color(99, 59, 30));

            this.seis.setColorNormal(new Color(91, 55, 21));
            this.seis.setColorHover(new Color(99, 59, 30));
            this.seis.setColorPressed(new Color(99, 59, 30));

            this.siete.setColorNormal(new Color(91, 55, 21));
            this.siete.setColorHover(new Color(99, 59, 30));
            this.siete.setColorPressed(new Color(99, 59, 30));

            this.ocho.setColorNormal(new Color(91, 55, 21));
            this.ocho.setColorHover(new Color(99, 59, 30));
            this.ocho.setColorPressed(new Color(99, 59, 30));
        } else {
            this.siete.setColorNormal(new Color(91, 55, 21));
            this.siete.setColorHover(new Color(99, 59, 30));
            this.siete.setColorPressed(new Color(99, 59, 30));
        }
    }//GEN-LAST:event_sieteActionPerformed

    private void seisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seisMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(true);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);

    }//GEN-LAST:event_seisMousePressed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
//        new CambiaPanel(pnlPrincipal, new Formulariospanel.pnlAndroid());
        if (this.seis.isSelected()) {
            this.uno.setColorNormal(new Color(91, 55, 21));
            this.uno.setColorHover(new Color(99, 59, 30));
            this.uno.setColorPressed(new Color(99, 59, 30));

            this.dos.setColorNormal(new Color(91, 55, 21));
            this.dos.setColorHover(new Color(99, 59, 30));
            this.dos.setColorPressed(new Color(99, 59, 30));

            this.tres.setColorNormal(new Color(91, 55, 21));
            this.tres.setColorHover(new Color(99, 59, 30));
            this.tres.setColorPressed(new Color(99, 59, 30));

            this.cuatro.setColorNormal(new Color(91, 55, 21));
            this.cuatro.setColorHover(new Color(99, 59, 30));
            this.cuatro.setColorPressed(new Color(99, 59, 30));

            this.cinco.setColorNormal(new Color(91, 55, 21));
            this.cinco.setColorHover(new Color(99, 59, 30));
            this.cinco.setColorPressed(new Color(99, 59, 30));

            this.seis.setColorNormal(new Color(91, 55, 21));
            this.seis.setColorHover(new Color(99, 59, 30));
            this.seis.setColorPressed(new Color(99, 59, 30));

            this.siete.setColorNormal(new Color(91, 55, 21));
            this.siete.setColorHover(new Color(99, 59, 30));
            this.siete.setColorPressed(new Color(99, 59, 30));

            this.ocho.setColorNormal(new Color(91, 55, 21));
            this.ocho.setColorHover(new Color(99, 59, 30));
            this.ocho.setColorPressed(new Color(99, 59, 30));
        } else {
            this.seis.setColorNormal(new Color(91, 55, 21));
            this.seis.setColorHover(new Color(99, 59, 30));
            this.seis.setColorPressed(new Color(99, 59, 30));
        }
    }//GEN-LAST:event_seisActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
//        new CambiaPanel(pnlPrincipal, new paneles.pnlMarket());
        if (this.cinco.isSelected()) {
            this.uno.setColorNormal(new Color(91, 55, 21));
            this.uno.setColorHover(new Color(99, 59, 30));
            this.uno.setColorPressed(new Color(99, 59, 30));

            this.dos.setColorNormal(new Color(91, 55, 21));
            this.dos.setColorHover(new Color(99, 59, 30));
            this.dos.setColorPressed(new Color(99, 59, 30));

            this.tres.setColorNormal(new Color(91, 55, 21));
            this.tres.setColorHover(new Color(99, 59, 30));
            this.tres.setColorPressed(new Color(99, 59, 30));

            this.cuatro.setColorNormal(new Color(91, 55, 21));
            this.cuatro.setColorHover(new Color(99, 59, 30));
            this.cuatro.setColorPressed(new Color(99, 59, 30));

            this.cinco.setColorNormal(new Color(91, 55, 21));
            this.cinco.setColorHover(new Color(99, 59, 30));
            this.cinco.setColorPressed(new Color(99, 59, 30));

            this.seis.setColorNormal(new Color(91, 55, 21));
            this.seis.setColorHover(new Color(99, 59, 30));
            this.seis.setColorPressed(new Color(99, 59, 30));

            this.siete.setColorNormal(new Color(91, 55, 21));
            this.siete.setColorHover(new Color(99, 59, 30));
            this.siete.setColorPressed(new Color(99, 59, 30));

            this.ocho.setColorNormal(new Color(91, 55, 21));
            this.ocho.setColorHover(new Color(99, 59, 30));
            this.ocho.setColorPressed(new Color(99, 59, 30));
        } else {
            this.cinco.setColorNormal(new Color(91, 55, 21));
            this.cinco.setColorHover(new Color(99, 59, 30));
            this.cinco.setColorPressed(new Color(99, 59, 30));
        }
    }//GEN-LAST:event_cincoActionPerformed

    private void cincoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(true);
        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_cincoMousePressed

    private void cuatroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatroMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(true);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_cuatroMousePressed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
//        new CambiaPanel(pnlPrincipal, new paneles.pnlFeeBack());
        if (this.cuatro.isSelected()) {
            this.uno.setColorNormal(new Color(91, 55, 21));
            this.uno.setColorHover(new Color(99, 59, 30));
            this.uno.setColorPressed(new Color(99, 59, 30));

            this.dos.setColorNormal(new Color(91, 55, 21));
            this.dos.setColorHover(new Color(99, 59, 30));
            this.dos.setColorPressed(new Color(99, 59, 30));

            this.tres.setColorNormal(new Color(91, 55, 21));
            this.tres.setColorHover(new Color(99, 59, 30));
            this.tres.setColorPressed(new Color(99, 59, 30));

            this.cuatro.setColorNormal(new Color(91, 55, 21));
            this.cuatro.setColorHover(new Color(99, 59, 30));
            this.cuatro.setColorPressed(new Color(99, 59, 30));

            this.cinco.setColorNormal(new Color(91, 55, 21));
            this.cinco.setColorHover(new Color(99, 59, 30));
            this.cinco.setColorPressed(new Color(99, 59, 30));

            this.seis.setColorNormal(new Color(91, 55, 21));
            this.seis.setColorHover(new Color(99, 59, 30));
            this.seis.setColorPressed(new Color(99, 59, 30));

            this.siete.setColorNormal(new Color(91, 55, 21));
            this.siete.setColorHover(new Color(99, 59, 30));
            this.siete.setColorPressed(new Color(99, 59, 30));

            this.ocho.setColorNormal(new Color(91, 55, 21));
            this.ocho.setColorHover(new Color(99, 59, 30));
            this.ocho.setColorPressed(new Color(99, 59, 30));
        } else {
            this.cuatro.setColorNormal(new Color(91, 55, 21));
            this.cuatro.setColorHover(new Color(99, 59, 30));
            this.cuatro.setColorPressed(new Color(99, 59, 30));
        }
    }//GEN-LAST:event_cuatroActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void uno1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uno1MousePressed
        new CambiaPanel(pnlPrincipal, new Formulariospanel.pnlraza());
    }//GEN-LAST:event_uno1MousePressed

    private void uno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uno1ActionPerformed

    }//GEN-LAST:event_uno1ActionPerformed

    private void tres1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tres1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tres1MousePressed

    private void tres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tres1ActionPerformed
        new CambiaPanel(pnlPrincipal, new Formulariospanel.pnlvaca());
    }//GEN-LAST:event_tres1ActionPerformed

    private void dos1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dos1MousePressed

    }//GEN-LAST:event_dos1MousePressed

    private void dos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dos1ActionPerformed
        new CambiaPanel(pnlPrincipal, new Formulariospanel.pnltoro());
    }//GEN-LAST:event_dos1ActionPerformed

    private void cinco1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cinco1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinco1MousePressed

    private void cinco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinco1ActionPerformed
//        volver.setVisible(false);
//         JOptionPane.showMessageDialog(null, "error");

        pnlMenu.setVisible(true);
        pnlPrincipal.removeAll();
        new CambiaPanel(pnlPrincipal, new Formulariospanel.pnlHome());

         //        if (this.uno1.isSelected()) {
        ////            volver.setVisible(true);
        //           pnlPrincipal.removeAll();
        //           pnlMenu.setVisible(true);
        //        } else if(this.dos1.isSelected()){
        //            pnlPrincipal.removeAll();
        //           pnlMenu.setVisible(true);          
        //        } else if(this.dos1.isSelected()){
        //            pnlPrincipal.removeAll();
        //           pnlMenu.setVisible(true); 
        //           } else if(this.tres1.isSelected()){
        //            pnlPrincipal.removeAll();
        //           pnlMenu.setVisible(true); 
        //           } else if(this.cuatro1.isSelected()){
        //            pnlPrincipal.removeAll();
        //           pnlMenu.setVisible(true); 
        //           }

    }//GEN-LAST:event_cinco1ActionPerformed

    private void ocho1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocho1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ocho1MousePressed

    private void ocho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocho1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ocho1ActionPerformed

    private void siete1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siete1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_siete1MousePressed

    private void siete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siete1ActionPerformed

    private void seis1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seis1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_seis1MousePressed

    private void seis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seis1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seis1ActionPerformed

    private void cuatro1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatro1MousePressed
        new CambiaPanel(pnlPrincipal, new Formulariospanel.pnlnacido());


    }//GEN-LAST:event_cuatro1MousePressed

    private void cuatro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatro1ActionPerformed

    }//GEN-LAST:event_cuatro1ActionPerformed

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_volverMouseEntered

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked

    }//GEN-LAST:event_volverMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void CerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarsesionMouseClicked

        AnimationClass internet = new AnimationClass();
        internet.jLabelXRight(-100, 10, 10, 5, Cerrarsesion);

        AnimationClass internett = new AnimationClass();
        internett.jLabelXLeft(10, -100, 10, 5, Cerrarsesion);
        
//        Principal123 prin = new Principal123();
//        prin.dispose();
        this.dispose();
        
        Login log = new Login();
        log.setVisible(true);
        
        

    }//GEN-LAST:event_CerrarsesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal123.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal123.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal123.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal123.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
//                    Login obj = new Login();
//                    obj.dispose();
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new Principal123().setVisible(true);

                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal123.class
                            .getName()).log(Level.SEVERE, null, ex);
                }

//                try {
//                    UIManager.setLookAndFeel(new MaterialLookAndFeel());
//                } catch (UnsupportedLookAndFeelException e) {
//                    e.printStackTrace();
//                }
////                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cerrarsesion;
    private rsbuttom.RSButtonMetro cinco;
    private rsbuttom.RSButtonMetro cinco1;
    private rsbuttom.RSButtonMetro cuatro;
    private rsbuttom.RSButtonMetro cuatro1;
    private rsbuttom.RSButtonMetro dos;
    private rsbuttom.RSButtonMetro dos1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private rsbuttom.RSButtonMetro ocho;
    private rsbuttom.RSButtonMetro ocho1;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMenu1;
    private javax.swing.JPanel pnlPrincipal;
    private rsbuttom.RSButtonMetro seis;
    private rsbuttom.RSButtonMetro seis1;
    private rsbuttom.RSButtonMetro siete;
    private rsbuttom.RSButtonMetro siete1;
    private rsbuttom.RSButtonMetro tres;
    private rsbuttom.RSButtonMetro tres1;
    private rsbuttom.RSButtonMetro uno;
    private rsbuttom.RSButtonMetro uno1;
    private javax.swing.JLabel volver;
    // End of variables declaration//GEN-END:variables
}
