/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulariospanel;

import Controlador.Conexion;
import Mensajes.ErrorAlertarea;
import Mensajes.ErrorAlertpotrero;
import static Mensajes.ErrorAlertpotrero.Potreros;
import Mensajes.SuccessAlert;
import Mensajes.WarningAlertCerrar;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import principal.Principal123;

/**
 *
 * @author RojeruSan
 */
public class pnlpotrero extends javax.swing.JPanel {

    public pnlpotrero() {
        initComponents();
//Razas.removeAllItems();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre_potrero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        area_hectareas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fuentes_agua = new javax.swing.JTextField();
        tipo_pasto = new javax.swing.JTextField();
        topografia = new javax.swing.JTextField();
        pastoreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        agregar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(667, 519));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(114, 76, 33));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Formulario de Potrero");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(114, 76, 33));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");

        nombre_potrero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre_potrero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_potreroActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(114, 76, 33));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripción: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Area de Hectareas:");

        area_hectareas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        area_hectareas.setToolTipText("Numeros");
        area_hectareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area_hectareasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fuente de agua:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo de pasto:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Topografía:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pastoreo:");

        fuentes_agua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fuentes_agua.setToolTipText("Numeros");
        fuentes_agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuentes_aguaActionPerformed(evt);
            }
        });

        tipo_pasto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipo_pasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_pastoActionPerformed(evt);
            }
        });

        topografia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        topografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topografiaActionPerformed(evt);
            }
        });

        pastoreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pastoreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastoreoActionPerformed(evt);
            }
        });

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(area_hectareas, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(fuentes_agua, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(nombre_potrero, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topografia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo_pasto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pastoreo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre_potrero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tipo_pasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(area_hectareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(topografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(pastoreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fuentes_agua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/btnagregar.jpg"))); // NOI18N
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/btnbuscar.jpg"))); // NOI18N
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/btnlimpiar.jpg"))); // NOI18N
        limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/btnmodificar.jpg"))); // NOI18N
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_potreroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_potreroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_potreroActionPerformed

    private void area_hectareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area_hectareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_area_hectareasActionPerformed

    private void fuentes_aguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuentes_aguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuentes_aguaActionPerformed

    private void tipo_pastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_pastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_pastoActionPerformed

    private void topografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topografiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topografiaActionPerformed

    private void pastoreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastoreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pastoreoActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed

        if (nombre_potrero.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Complete el espacio vacio!!");
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL NOMBRE DEL POTRERO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);
            //            modificar.setEnabled(false);        
        } else if (descripcion.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Complete el espacio vacio!!");
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE LA DESCRIPCIÓN DEL POTRERO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);
            //            modificar.setEnabled(false);        
        } else if (area_hectareas.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL AREA DE HECTAREAS");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (fuentes_agua.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE LA FUENTE DE AGUA");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (tipo_pasto.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL TIPO DE PASTO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (topografia.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE LA TOPOGRAFIA");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (pastoreo.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL PASTOREO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else {
            try {
                Controlador.Conexion con = new Controlador.Conexion();
                con.ConexionPostgres();
                //JOptionPane.showMessageDialog(null, "El Area está repetida");

                con.actualizar("insert into potrero (nombre_potrero,descripcion,area_hectareas,fuentes_agua,tipo_pasto,topografia,pastoreo"
                        + ") values('" + nombre_potrero.getText() + "', '" + descripcion.getText() + "'," + area_hectareas.getText()
                        + "," + fuentes_agua.getText() + ",'" + tipo_pasto.getText() + "','" + topografia.getText() + "','" + pastoreo.getText() + "')");
                //                    JOptionPane.showMessageDialog(null, "Area Registrada");
                SuccessAlert sa = new SuccessAlert(new principal.Principal123(), true);
                sa.titulo.setText("POTRERO REGISTRADO!");
                sa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
                sa.titulo.setForeground(new java.awt.Color(153, 153, 153));
                sa.setVisible(true);

                nombre_potrero.setText("");
                descripcion.setText("");
                area_hectareas.setText("");
                fuentes_agua.setText("");
                tipo_pasto.setText("");
                topografia.setText("");
                pastoreo.setText("");

                con.cerrar();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_agregarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
   
        if (nombre_potrero.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Complete el espacio vacio!!");
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL NOMBRE DEL POTRERO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);
            //            modificar.setEnabled(false);        
        } else if (descripcion.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Complete el espacio vacio!!");
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE LA DESCRIPCIÓN DEL POTRERO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);
            //            modificar.setEnabled(false);        
        } else if (area_hectareas.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL AREA DE HECTAREAS");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (fuentes_agua.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE LA FUENTE DE AGUA");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (tipo_pasto.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL TIPO DE PASTO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (topografia.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE LA TOPOGRAFIA");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (pastoreo.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL PASTOREO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else {

            modificar.setEnabled(false);

            try {
                Conexion con = new Conexion();
                con.ConexionPostgres();

                String sql = ("Update potrero set nombre_potrero  = '" + nombre_potrero.getText() 
                        + "', descripcion = '" + descripcion.getText() 
                        + "', area_hectareas = " + area_hectareas.getText() 
                        + ", fuentes_agua = '" + fuentes_agua.getText() 
                        + "', tipo_pasto = '" + tipo_pasto.getText() 
                        + "', topografia = '" + topografia.getText() 
                        + "', pastoreo = '" + pastoreo.getText() +
                        "' where nombre_potrero = '" +nombre_potrero.getText()+  "'");

                con.actualizar(sql);
//                JOptionPane.showMessageDialog(null, "INFORMACION MODIFICADA!");
                SuccessAlert sa = new SuccessAlert(new principal.Principal123(), true);
                sa.titulo.setText("POTRERO MODIFICADO"
                        + "!");
                sa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
                sa.titulo.setForeground(new java.awt.Color(153, 153, 153));
                sa.setVisible(true);

                nombre_potrero.setText("");
                descripcion.setText("");
                area_hectareas.setText("");
                fuentes_agua.setText("");
                tipo_pasto.setText("");
                topografia.setText("");
                pastoreo.setText("");

                con.cerrar();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            }

            modificar.setEnabled(false);
//            cedula.setEnabled(true);
            agregar.setEnabled(true);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        ErrorAlertpotrero obj = new ErrorAlertpotrero(new principal.Principal123(), true);
        obj.titulo.setText("ESCOJE EL POTRERO: ");
        obj.titulo.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        obj.titulo.setForeground(new java.awt.Color(153, 153, 153));
        obj.setVisible(true);

        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
//            System.out.println("Select * from potrero where nombre_potrero = '\" + obj.Razas.getSelectedItem().toString() + ");
            ResultSet rs = con.consultar("Select * from potrero where nombre_potrero = '" + obj.Potreros.getSelectedItem().toString() + "' ");
            
            if (rs.next()) {

                nombre_potrero.setText(rs.getString("nombre_potrero"));
                descripcion.setText(rs.getString("descripcion"));
                area_hectareas.setText(rs.getString("area_hectareas"));
                fuentes_agua.setText(rs.getString("fuentes_agua"));
                tipo_pasto.setText(rs.getString("tipo_pasto"));
                topografia.setText(rs.getString("topografia"));
                pastoreo.setText(rs.getString("pastoreo"));

                modificar.setEnabled(true);
                agregar.setEnabled(false);
//                id.setEnabled(false);

            } else {
//                JOptionPane.showMessageDialog(null, "El Area no existe");
                WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
                wa.titulo.setText("¡¡POTRERO NO REGISTRADO!!");
                wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
                wa.setVisible(true);

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pnlpotrero.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(pnlpotrero.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(pnlpotrero.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(pnlpotrero.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buscarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        nombre_potrero.setText("");
        descripcion.setText("");
        area_hectareas.setText("");
        fuentes_agua.setText("");
        tipo_pasto.setText("");
        topografia.setText("");
        pastoreo.setText("");
        
    }//GEN-LAST:event_limpiarActionPerformed

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
Potreros.removeAllItems(); 
        
    }//GEN-LAST:event_modificarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField area_hectareas;
    private javax.swing.JButton buscar;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JTextField fuentes_agua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre_potrero;
    private javax.swing.JTextField pastoreo;
    private javax.swing.JTextField tipo_pasto;
    private javax.swing.JTextField topografia;
    // End of variables declaration//GEN-END:variables
}
