/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulariospanel;

import Controlador.Conexion;
import Mensajes.ErrorAlertarea;
import Mensajes.ErrorAlertraza;
import Mensajes.ErrorAlerttoro;
import Mensajes.SuccessAlert;
import Mensajes.WarningAlertCerrar;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author RojeruSan
 */
public class pnltoro extends javax.swing.JPanel {

    public pnltoro() {
        initComponents();

        fecha_castrado.setVisible(false);

        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            String query = "select nombre_raza from raza";
            ResultSet rs = con.consultar(query);
            while (rs.next()) {
                raza_id_raza.addItem(rs.getString(1));

            }

            String query2 = "select nombre_potrero from potrero";
            ResultSet rs2 = con.consultar(query2);
            while (rs2.next()) {
                potrero_idpotrero.addItem(rs2.getString(1));

            }
        } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(pnltoro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    //va el codigo 
    //OBTENIENDO EL ID DEL POTRERO Y DE LA RAZA
    //OBTENIENDO EL ID DEL POTRERO Y DE LA RAZA
    public static String obteneriddelpotrero(JComboBox nombredelcombopotrero) {
        String iddelpotrero = "";

        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();

            ResultSet rs3 = con.consultar("select idpotrero from potrero where nombre_potrero = '" + potrero_idpotrero.getSelectedItem().toString() + "' ");

            if (rs3.next()) {
                iddelpotrero = rs3.getString(1);
            }

        } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(pnltoro.class.getName()).log(Level.SEVERE, null, ex);
        }

        return iddelpotrero;
    }

    public static String obteneriddelaraza(JComboBox nombredelcomboraza) {
        String iddelaraza = "";

        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();

            ResultSet rs4 = con.consultar("select id_raza from raza where nombre_raza = '" + raza_id_raza.getSelectedItem().toString() + "' ");

            if (rs4.next()) {
                iddelaraza = rs4.getString(1);
            }

        } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(pnltoro.class.getName()).log(Level.SEVERE, null, ex);
        }

        return iddelaraza;
    }

    //OBTENIENDO NOMBRE DE LA RAZA Y EL POTRERO
    public static String obtenernombredelpotrero(String iddelpotrero) {
        String nombredelpotrero = "";

        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();

            ResultSet rs33 = con.consultar("select nombre_potrero from potrero where idpotrero = '" + iddelpotrero + "' ");

            if (rs33.next()) {
                nombredelpotrero = rs33.getString(1);
            }

        } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(pnltoro.class.getName()).log(Level.SEVERE, null, ex);
        }

        return nombredelpotrero;
    }

    public static String obtenernombredelaraza(String iddelaraza) {
        String nombredelaraza = "";

        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();

            ResultSet rs4 = con.consultar("select nombre_raza from raza where id_raza = '" + iddelaraza + "' ");

            if (rs4.next()) {
                nombredelaraza = rs4.getString(1);
            }

        } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(pnltoro.class.getName()).log(Level.SEVERE, null, ex);
        }

        return nombredelaraza;
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre_toro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idtoro = new javax.swing.JTextField();
        no_siniga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        no_registro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        raza_id_raza = new javax.swing.JComboBox();
        potrero_idpotrero = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ingreso_granja = new rojeru_san.componentes.RSDateChooser();
        ingreso_sist = new rojeru_san.componentes.RSDateChooser();
        motivo_ing = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tipo_concepcion = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        fecha_castrado = new rojeru_san.componentes.RSDateChooser();
        jPanel4 = new javax.swing.JPanel();
        semen = new javax.swing.JRadioButton();
        reproduccion = new javax.swing.JRadioButton();
        castrado = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fecha_nac = new rojeru_san.componentes.RSDateChooser();
        tatuaje_der = new javax.swing.JRadioButton();
        tatuaje_izq = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        peso_toro = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        motivo_salida = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        agregar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(667, 519));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(188, 30, 44));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");

        nombre_toro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre_toro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_toroActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(114, 76, 33));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Sinigán: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Raza:");

        idtoro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idtoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtoroActionPerformed(evt);
            }
        });

        no_siniga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no_siniga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_sinigaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Id Toro:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("No. Registro:");

        no_registro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_registroActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Potrero:");

        raza_id_raza.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        raza_id_raza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));

        potrero_idpotrero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        potrero_idpotrero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ingreso al sistema:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Motivo de ingreso:");

        ingreso_granja.setColorBackground(new java.awt.Color(255, 102, 102));
        ingreso_granja.setColorButtonHover(new java.awt.Color(255, 102, 102));
        ingreso_granja.setColorDiaActual(new java.awt.Color(255, 102, 102));
        ingreso_granja.setColorForeground(new java.awt.Color(102, 102, 102));

        ingreso_sist.setColorBackground(new java.awt.Color(255, 102, 102));
        ingreso_sist.setColorButtonHover(new java.awt.Color(255, 102, 102));
        ingreso_sist.setColorDiaActual(new java.awt.Color(255, 102, 102));
        ingreso_sist.setColorForeground(new java.awt.Color(102, 102, 102));

        motivo_ing.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        motivo_ing.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Compra", "Nacimiento", " " }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Color:");

        color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tatuaje del Toro:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tipo de concepción:");

        tipo_concepcion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tipo_concepcion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Empadre Múltiple", "Inseminación Artificial", "Monta Natural", "Trasplante de Embriones" }));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(188, 30, 44));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Reproducción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Semen");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Reproducción");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Castrado");

        fecha_castrado.setColorBackground(new java.awt.Color(255, 102, 102));
        fecha_castrado.setColorButtonHover(new java.awt.Color(255, 102, 102));
        fecha_castrado.setColorDiaActual(new java.awt.Color(255, 102, 102));
        fecha_castrado.setColorForeground(new java.awt.Color(102, 102, 102));
        fecha_castrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fecha_castradoMouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(114, 76, 33));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        semen.setBackground(new java.awt.Color(188, 30, 44));
        semen.setText("jRadioButton1");
        semen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semenActionPerformed(evt);
            }
        });

        reproduccion.setBackground(new java.awt.Color(188, 30, 44));
        reproduccion.setText("jRadioButton1");
        reproduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproduccionActionPerformed(evt);
            }
        });

        castrado.setBackground(new java.awt.Color(188, 30, 44));
        castrado.setText("jRadioButton1");
        castrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                castradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(castrado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(fecha_castrado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(semen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(semen, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(reproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(castrado))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha_castrado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Ingreso a la granja:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Id Toro:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de nacimiento:");

        fecha_nac.setColorBackground(new java.awt.Color(255, 102, 102));
        fecha_nac.setColorButtonHover(new java.awt.Color(255, 102, 102));
        fecha_nac.setColorDiaActual(new java.awt.Color(255, 102, 102));
        fecha_nac.setColorForeground(new java.awt.Color(102, 102, 102));

        tatuaje_der.setBackground(new java.awt.Color(188, 30, 44));
        tatuaje_der.setText("jRadioButton1");
        tatuaje_der.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tatuaje_derActionPerformed(evt);
            }
        });

        tatuaje_izq.setBackground(new java.awt.Color(188, 30, 44));
        tatuaje_izq.setText("jRadioButton1");
        tatuaje_izq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tatuaje_izqActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Der");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Izq");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Peso:");

        peso_toro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        peso_toro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso_toroActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Motivo de salida:");

        motivo_salida.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        motivo_salida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Muerte", "Venta", "Descarte" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel24))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tipo_concepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(motivo_ing, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(color)
                                    .addComponent(peso_toro)
                                    .addComponent(motivo_salida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(141, 141, 141)
                                        .addComponent(raza_id_raza, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(121, 121, 121)
                                        .addComponent(potrero_idpotrero, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(no_registro, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                        .addComponent(nombre_toro, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                        .addComponent(no_siniga)))
                                .addComponent(idtoro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)
                            .addComponent(jLabel23)
                            .addComponent(jLabel2)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(379, 379, 379)
                                .addComponent(jLabel18))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel13))
                                    .addGap(49, 49, 49)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ingreso_sist, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(ingreso_granja, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(fecha_nac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tatuaje_der, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tatuaje_izq, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fecha_nac, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ingreso_granja, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ingreso_sist, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel4)
                            .addComponent(tatuaje_der)
                            .addComponent(jLabel6)
                            .addComponent(tatuaje_izq)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel23))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(idtoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre_toro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(no_siniga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel12))
                            .addComponent(no_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(raza_id_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(3, 3, 3))
                            .addComponent(potrero_idpotrero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(motivo_ing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(tipo_concepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(color)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(peso_toro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(motivo_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 810, 350));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(188, 30, 44));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Formulario de Toro");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 420, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/btnagregartoro.jpg"))); // NOI18N
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/btnbuscartoro.jpg"))); // NOI18N
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/btnlimpiartoro.jpg"))); // NOI18N
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/btnmodificartoro.jpg"))); // NOI18N
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 610, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toroicons.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 150, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_toroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_toroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_toroActionPerformed

    private void idtoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtoroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtoroActionPerformed

    private void no_sinigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_sinigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_sinigaActionPerformed

    private void no_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_registroActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed

        if (idtoro.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Complete el espacio vacio!!");
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL ID DEL TORO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);
            
            //            modificar.setEnabled(false);        
        } else if (nombre_toro.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Complete el espacio vacio!!");
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL NOMBRE DEL TORO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);
            //            modificar.setEnabled(false);        
        } else if (no_siniga.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL NUMERO SINIGAN");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (no_registro.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL NUMERO DE REGISTRO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (raza_id_raza.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, ESCOJA EL TIPO DE RAZA");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (potrero_idpotrero.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, ESCOJA EL POTRERO ");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (motivo_ing.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, ESCOJA EL MOTIVO DE INGRESO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (tipo_concepcion.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, ESCOJA EL TIPO DE CONCEPCIÓN");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else {
            try {
                Controlador.Conexion con = new Controlador.Conexion();
                con.ConexionPostgres();
                //JOptionPane.showMessageDialog(null, "El Area está repetida");

//                Boolean seme = semen.isSelected();
//                Boolean repro = reproduccion.isSelected();
//                Boolean castro = castrado.isSelected();
                Boolean der = tatuaje_der.isSelected();
                Boolean izq = tatuaje_izq.isSelected();
                con.actualizar("insert into toro (idtoro,potrero_idpotrero,raza_id_raza,no_siniga,nombre_toro"
                        + ",tatuaje,no_registro,fecha_nac,motivo_ing,ingreso_granja"
                        + ",ingreso_sist,color,tipo_concepcion,motivo_salida,peso_toro,tipo_reproduccion"
                        + ") values('" + idtoro.getText() + "', '"
                        + obteneriddelpotrero(potrero_idpotrero)
                        + "'," + obteneriddelaraza(raza_id_raza)
                        + "," + no_siniga.getText()
                        + ",'" + nombre_toro.getText()
                        + "','" + tatuaje
                        + "','" + no_registro.getText()
                        + "','" + fecha_nac.getDatoFecha() + "','"
                        + motivo_ing.getSelectedItem().toString()
                        + "','" + ingreso_granja.getDatoFecha()
                        + "','" + ingreso_sist.getDatoFecha()
                        + "','" + color.getText()
                        + "','" + tipo_concepcion.getSelectedItem().toString() 
                        + "','" + motivo_salida.getSelectedItem().toString() 
                        + "','" + peso_toro.getText()
                        + "','" +  tipo_reproduccion + "')");
//                 + "','" + 
                //                    JOptionPane.showMessageDialog(null, "Area Registrada");  semen,reproduccion,castrado
                SuccessAlert sa = new SuccessAlert(new principal.Principal123(), true);
                sa.titulo.setText("TORO REGISTRADO!");
                sa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
                sa.titulo.setForeground(new java.awt.Color(153, 153, 153));
                sa.setVisible(true);

                idtoro.setText("");
                nombre_toro.setText("");
                no_registro.setText("");
                no_siniga.setText("");
                color.setText("");
                motivo_ing.setSelectedIndex(0);
                tipo_concepcion.setSelectedIndex(0);
                tatuaje_der.setSelected(false);
                tatuaje_izq.setSelected(false);
                potrero_idpotrero.setSelectedIndex(0);
                raza_id_raza.setSelectedIndex(0);
                fecha_nac.setDatoFecha(null);
                ingreso_granja.setDatoFecha(null);
                ingreso_sist.setDatoFecha(null);
                semen.setSelected(false);
                reproduccion.setSelected(false);
                castrado.setSelected(false);
                tatuaje_der.setSelected(false);
                tatuaje_izq.setSelected(false);

                con.cerrar();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_agregarActionPerformed
    String tipo_reproduccion = "";
    private void reproduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproduccionActionPerformed
        semen.setSelected(false);
        castrado.setSelected(false);
        fecha_castrado.setVisible(false);
        tipo_reproduccion = "reproduccion";
    }//GEN-LAST:event_reproduccionActionPerformed

    private void semenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semenActionPerformed
        reproduccion.setSelected(true);
        castrado.setSelected(false);
        fecha_castrado.setVisible(false);
        tipo_reproduccion = "Semen";
    }//GEN-LAST:event_semenActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

        ErrorAlerttoro obj = new ErrorAlerttoro(new principal.Principal123(), true);
        obj.titulo.setText("ESCOJE EL TORO: ");
        obj.titulo.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        obj.titulo.setForeground(new java.awt.Color(153, 153, 153));
        obj.setVisible(true);

        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();

//            System.out.println("Select * from toro where idtoro = '" + obj.Razas.getSelectedItem().toString() + "' ");
            ResultSet rs = con.consultar("Select * from toro where nombre_toro = '" + obj.Toros.getSelectedItem().toString() + "' ");
            if (rs.next()) {

                idtoro.setText(rs.getString("idtoro"));
                nombre_toro.setText(rs.getString("nombre_toro"));
                no_registro.setText(rs.getString("no_registro"));
                no_siniga.setText(rs.getString("no_siniga"));
                color.setText(rs.getString("color"));
                fecha_nac.setDatoFecha(rs.getDate("fecha_nac"));
                ingreso_granja.setDatoFecha(rs.getDate("ingreso_granja"));
                ingreso_sist.setDatoFecha(rs.getDate("ingreso_sist"));
                motivo_ing.setSelectedItem(rs.getString(9));
                tipo_concepcion.setSelectedItem(rs.getString(13));
                tatuaje_der.setSelected(rs.getBoolean("tatuaje_der"));
                raza_id_raza.setSelectedItem(obtenernombredelaraza(rs.getString("raza_id_raza")));
                potrero_idpotrero.setSelectedItem(obtenernombredelpotrero(rs.getString("potrero_idpotrero")));
                semen.setSelected(rs.getBoolean("semen"));
                reproduccion.setSelected(rs.getBoolean("reproduccion"));
                castrado.setSelected(rs.getBoolean("castrado"));
                tatuaje_izq.setSelected(rs.getBoolean("tatuaje_izq"));
                modificar.setEnabled(true);
                agregar.setEnabled(false);
                idtoro.setEnabled(false);
//                id.setEnabled(false);

            } else {
//                JOptionPane.showMessageDialog(null, "El Area no existe");
                WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
                wa.titulo.setText("¡¡TORO NO REGISTRADO!!");
                wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
                wa.setVisible(true);

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pnlpotrero.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(pnlpotrero.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(pnlpotrero.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(pnlpotrero.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buscarActionPerformed

    private void castradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_castradoActionPerformed
        fecha_castrado.setVisible(true);
        semen.setSelected(false);
        reproduccion.setSelected(false);
        tipo_reproduccion = "Castrado";
    }//GEN-LAST:event_castradoActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        idtoro.setText("");
        nombre_toro.setText("");
        no_registro.setText("");
        no_siniga.setText("");
        color.setText("");
        motivo_ing.setSelectedIndex(0);
        tipo_concepcion.setSelectedIndex(0);
        tatuaje_der.setSelected(false);
        tatuaje_izq.setSelected(false);
        potrero_idpotrero.setSelectedIndex(0);
        raza_id_raza.setSelectedIndex(0);
        fecha_nac.setDatoFecha(null);
        ingreso_granja.setDatoFecha(null);
        ingreso_sist.setDatoFecha(null);
        semen.setSelected(false);
        reproduccion.setSelected(false);
        castrado.setSelected(false);
        tatuaje_der.setSelected(false);
        tatuaje_izq.setSelected(false);
        peso_toro.setText("");
        
    }//GEN-LAST:event_limpiarActionPerformed

    private void fecha_castradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecha_castradoMouseClicked
        semen.setSelected(false);
        reproduccion.setSelected(false);

    }//GEN-LAST:event_fecha_castradoMouseClicked

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        if (idtoro.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Complete el espacio vacio!!");
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL ID DE TORO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);
            //            modificar.setEnabled(false);        
        } else if (nombre_toro.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Complete el espacio vacio!!");
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL NOMBRE DEL TORO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);
            //            modificar.setEnabled(false);        
        } else if (no_siniga.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL NUMERO SINIGAN");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (no_registro.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL NUMERO DE REGISTRO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (raza_id_raza.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, ESCOJA LA RAZA DEL TORO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (potrero_idpotrero.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, ESCOJA EL POTRERO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (color.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL COLOR DEL TORO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (motivo_ing.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, ESCOJA EL MOTIVO DE INGRESO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (tipo_concepcion.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, ESCOJA EL TIPO DE CONCEPCIÓN");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else {

            modificar.setEnabled(false);

            try {
                Conexion con = new Conexion();
                con.ConexionPostgres();

                String sql = ("Update toro set potrero_idpotrero  = '"
                        + obteneriddelpotrero(potrero_idpotrero)
                        + "', raza_id_raza = '" + obteneriddelaraza(raza_id_raza)
                        + "', no_siniga = " + no_siniga.getText()
                        + ", nombre_toro = '" + nombre_toro.getText()
                        + "', tatuaje_der = '" + tatuaje_der.getText()
                        + "', no_registro = '" + no_registro.getText()
                        + "', fecha_nac = '" + fecha_nac.getDatoFecha()
                        + "', motivo_ing = '" + motivo_ing.getSelectedItem().toString()
                        + "', ingreso_granja = '" + ingreso_granja.getDatoFecha()
                        + "', ingreso_sist = '" + ingreso_sist.getDatoFecha()
                        + "', color = '" + color.getText()
                        + "', semen = '" + semen.getText()
                        + "', reproduccion = '" + reproduccion.getText()
                        + "', castrado = '" + castrado.getText()
                        + "', tipo_concepcion = '" + tipo_concepcion.getSelectedItem().toString()
                        + "', tatuaje_izq = '" + tatuaje_izq.getText()
                        + "' where idtoro = '" + idtoro.getText() + "'");
                System.out.print(sql);
                con.actualizar(sql);
//                JOptionPane.showMessageDialog(null, "INFORMACION MODIFICADA!");
                SuccessAlert sa = new SuccessAlert(new principal.Principal123(), true);
                sa.titulo.setText("TORO MODIFICADO");
                sa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
                sa.titulo.setForeground(new java.awt.Color(153, 153, 153));
                sa.setVisible(true);

                idtoro.setText("");
                nombre_toro.setText("");
                no_registro.setText("");
                no_siniga.setText("");
                color.setText("");
                motivo_ing.setSelectedIndex(0);
                tipo_concepcion.setSelectedIndex(0);
                tatuaje_der.setSelected(false);
                tatuaje_izq.setSelected(false);
                potrero_idpotrero.setSelectedIndex(0);
                raza_id_raza.setSelectedIndex(0);
                fecha_nac.setDatoFecha(null);
                ingreso_granja.setDatoFecha(null);
                ingreso_sist.setDatoFecha(null);
                semen.setSelected(false);
                reproduccion.setSelected(false);
                castrado.setSelected(false);
                tatuaje_der.setSelected(false);
                tatuaje_izq.setSelected(false);
                con.cerrar();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            }

            modificar.setEnabled(false);
//            cedula.setEnabled(true);
            agregar.setEnabled(true);
        }

    }//GEN-LAST:event_modificarActionPerformed
    String tatuaje = "";
    private void tatuaje_derActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tatuaje_derActionPerformed
//        tatuaje_der.setSelected(true);
//        tatuaje_izq.setSelected(false);

        if (tatuaje_der.isSelected() == true) {
            tatuaje = "Derecho";
            tatuaje_izq.setSelected(false);

        } else {
            tatuaje_izq.setSelected(true);
            tatuaje = "Izquierdo";
            tatuaje_der.setSelected(false);
        }

    }//GEN-LAST:event_tatuaje_derActionPerformed

    private void tatuaje_izqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tatuaje_izqActionPerformed

        if (tatuaje_izq.isSelected() == true) {
            tatuaje = "Izquierdo";
            tatuaje_der.setSelected(false);
        } else {
            tatuaje_der.setSelected(true);
            tatuaje = "Derecho";
            tatuaje_izq.setSelected(false);
        }

    }//GEN-LAST:event_tatuaje_izqActionPerformed

    private void peso_toroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso_toroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peso_toroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscar;
    private javax.swing.JRadioButton castrado;
    private javax.swing.JTextField color;
    private rojeru_san.componentes.RSDateChooser fecha_castrado;
    private rojeru_san.componentes.RSDateChooser fecha_nac;
    private javax.swing.JTextField idtoro;
    private rojeru_san.componentes.RSDateChooser ingreso_granja;
    private rojeru_san.componentes.RSDateChooser ingreso_sist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton modificar;
    private javax.swing.JComboBox motivo_ing;
    private javax.swing.JComboBox motivo_salida;
    private javax.swing.JTextField no_registro;
    private javax.swing.JTextField no_siniga;
    private javax.swing.JTextField nombre_toro;
    private javax.swing.JTextField peso_toro;
    public static javax.swing.JComboBox potrero_idpotrero;
    public static javax.swing.JComboBox raza_id_raza;
    private javax.swing.JRadioButton reproduccion;
    private javax.swing.JRadioButton semen;
    private javax.swing.JRadioButton tatuaje_der;
    private javax.swing.JRadioButton tatuaje_izq;
    private javax.swing.JComboBox tipo_concepcion;
    // End of variables declaration//GEN-END:variables
}
