/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulariospanel;

import Controlador.Conexion;
import static Formulariospanel.pnltoro.obteneriddelaraza;
import static Formulariospanel.pnltoro.obteneriddelpotrero;
import static Formulariospanel.pnltoro.obtenernombredelaraza;
import static Formulariospanel.pnltoro.obtenernombredelpotrero;
import static Formulariospanel.pnltoro.potrero_idpotrero;
import static Formulariospanel.pnltoro.raza_id_raza;
import Mensajes.ErrorAlertarea;
import Mensajes.ErrorAlertvaca;
import Mensajes.SuccessAlert;
import Mensajes.WarningAlertCerrar;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author RojeruSan
 */
public class pnlvaca extends javax.swing.JPanel {

    public pnlvaca() {
        initComponents();
tipo.repaint(100, 100, 120, 130);
tipo.repaint(100);
tipo.repaint(100, 100, 111, 222, 100);
try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            String query = "select nombre_raza from raza";
            ResultSet rs = con.consultar(query);
            while (rs.next()) {
                raza_id_raza.addItem(rs.getString(1));

            }

            String query2 = "select nombre_potrero from potrero";
            ResultSet rs2 = con.consultar(query2);
            while (rs2.next()) {
                potrero_idpotrero.addItem(rs2.getString(1));

            }
        } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(pnltoro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    //OBTENIENDO EL ID DEL POTRERO Y DE LA RAZA
    //OBTENIENDO EL ID DEL POTRERO Y DE LA RAZA
    public static String obteneriddelpotrero(JComboBox nombredelcombopotrero) {
        String iddelpotrero = "";

        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();

            ResultSet rs3 = con.consultar("select idpotrero from potrero where nombre_potrero = '" + potrero_idpotrero.getSelectedItem().toString() + "' ");

            if (rs3.next()) {
                iddelpotrero = rs3.getString(1);
            }

        } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(pnltoro.class.getName()).log(Level.SEVERE, null, ex);
        }

        return iddelpotrero;
    }

    public static String obteneriddelaraza(JComboBox nombredelcomboraza) {
        String iddelaraza = "";

        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();

            ResultSet rs4 = con.consultar("select id_raza from raza where nombre_raza = '" + raza_id_raza.getSelectedItem().toString() + "' ");

            if (rs4.next()) {
                iddelaraza = rs4.getString(1);
            }

        } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(pnltoro.class.getName()).log(Level.SEVERE, null, ex);
        }

        return iddelaraza;
    }

    //OBTENIENDO NOMBRE DE LA RAZA Y EL POTRERO
    public static String obtenernombredelpotrero(String iddelpotrero) {
        String nombredelpotrero = "";

        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();

            ResultSet rs33 = con.consultar("select idpotrero from potrero where nombre_potrero = " + potrero_idpotrero.getSelectedItem().toString() + " ");

            if (rs33.next()) {
                nombredelpotrero = rs33.getString(1);
            }

        } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(pnltoro.class.getName()).log(Level.SEVERE, null, ex);
        }

        return nombredelpotrero;
    }

    public static String obtenernombredelaraza(String iddelaraza) {
        String nombredelaraza = "";

        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();

            ResultSet rs4 = con.consultar("select id_raza from raza where nombre_raza = '" + raza_id_raza.getSelectedItem().toString() + "' ");

            if (rs4.next()) {
                nombredelaraza = rs4.getString(1);
            }

        } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(pnltoro.class.getName()).log(Level.SEVERE, null, ex);
        }

        return nombredelaraza;
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre_vaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idvaca = new javax.swing.JTextField();
        no_siniga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        no_registro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        raza_id_raza = new javax.swing.JComboBox();
        potrero_idpotrero = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ingreso_granja = new rojeru_san.componentes.RSDateChooser();
        ingreso_sist = new rojeru_san.componentes.RSDateChooser();
        motivo_ing = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tipo_concepcion = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        fecha_nac = new rojeru_san.componentes.RSDateChooser();
        jLabel4 = new javax.swing.JLabel();
        tatuaje_der = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        tatuaje_izq = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        agregar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tipo = new componentes.org1.bolivia.combo.SComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(667, 519));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");

        nombre_vaca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre_vaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_vacaActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(114, 76, 33));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Sinigán: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Raza:");

        idvaca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idvaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idvacaActionPerformed(evt);
            }
        });

        no_siniga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no_siniga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_sinigaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Id vaca:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("No. Registro:");

        no_registro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_registroActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Potrero:");

        raza_id_raza.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        raza_id_raza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));

        potrero_idpotrero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        potrero_idpotrero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ingreso a la granja:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ingreso al sistema:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Motivo de ingreso:");

        ingreso_granja.setColorBackground(new java.awt.Color(51, 51, 51));
        ingreso_granja.setColorButtonHover(new java.awt.Color(0, 0, 0));
        ingreso_granja.setColorDiaActual(new java.awt.Color(0, 0, 0));
        ingreso_granja.setColorForeground(new java.awt.Color(0, 0, 0));

        ingreso_sist.setColorBackground(new java.awt.Color(51, 51, 51));
        ingreso_sist.setColorButtonHover(new java.awt.Color(0, 0, 0));
        ingreso_sist.setColorDiaActual(new java.awt.Color(0, 0, 0));
        ingreso_sist.setColorForeground(new java.awt.Color(0, 0, 0));

        motivo_ing.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        motivo_ing.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Compra", "Nacimiento", " " }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Color de la vaca:");

        color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tatuaje de la vaca:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tipo de concepción:");

        tipo_concepcion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tipo_concepcion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Empadre Múltiple", "Inseminación Artificial", "Monta Natural", "Trasplante de Embriones" }));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Fecha de nacimiento:");

        fecha_nac.setColorBackground(new java.awt.Color(51, 51, 51));
        fecha_nac.setColorButtonHover(new java.awt.Color(0, 0, 0));
        fecha_nac.setColorDiaActual(new java.awt.Color(0, 0, 0));
        fecha_nac.setColorForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Der");

        tatuaje_der.setBackground(new java.awt.Color(0, 0, 0));
        tatuaje_der.setText("jRadioButton1");
        tatuaje_der.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tatuaje_derActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Izq");

        tatuaje_izq.setBackground(new java.awt.Color(0, 0, 0));
        tatuaje_izq.setText("jRadioButton1");
        tatuaje_izq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tatuaje_izqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(potrero_idpotrero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(raza_id_raza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(no_registro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(no_siniga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_vaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idvaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(fecha_nac, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ingreso_granja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(ingreso_sist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(motivo_ing, 0, 152, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipo_concepcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tatuaje_der, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tatuaje_izq, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(color, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ingreso_granja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(idvaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(5, 5, 5))
                            .addComponent(ingreso_sist, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(motivo_ing, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(tipo_concepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(tatuaje_der)
                                .addComponent(jLabel6)
                                .addComponent(tatuaje_izq))
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre_vaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(no_siniga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(no_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(raza_id_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(potrero_idpotrero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(fecha_nac, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 780, 270));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Formulario de Vaca");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 400, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/btnagregarvaca.jpg"))); // NOI18N
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/btnbuscarvaca.jpg"))); // NOI18N
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/btnlimpiarvaca.jpg"))); // NOI18N
        limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/btnmodificarvaca.jpg"))); // NOI18N
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 620, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vacaformula.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 150, 100));

        tipo.setBackground(new java.awt.Color(0, 0, 0));
        tipo.setEditable(true);
        tipo.setForeground(new java.awt.Color(0, 0, 0));
        tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TIPO USUARIO", "ADMINISTRADOR", "NORMAL" }));
        tipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 240, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_vacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_vacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_vacaActionPerformed

    private void idvacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idvacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idvacaActionPerformed

    private void no_sinigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_sinigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_sinigaActionPerformed

    private void no_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_registroActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        ErrorAlertvaca obj = new ErrorAlertvaca(new principal.Principal123(), true);
        obj.titulo.setText("ESCOJE LA VACA: ");
        obj.titulo.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        obj.titulo.setForeground(new java.awt.Color(153, 153, 153));
        obj.setVisible(true);

        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            ResultSet rs = con.consultar("Select * from vaca where nombre_vaca = '" + obj.Vacas.getSelectedItem().toString() + "' ");
            if (rs.next()) {

                idvaca.setText(rs.getString("idvaca"));
                potrero_idpotrero.setSelectedItem(obtenernombredelpotrero(rs.getString("potrero_idpotrero")));
                raza_id_raza.setSelectedItem(obtenernombredelaraza(rs.getString("raza_id_raza")));
                no_siniga.setText(rs.getString("no_siniga"));
                nombre_vaca.setText(rs.getString("nombre_vaca"));
                no_registro.setText(rs.getString("no_registro"));
                fecha_nac.setDatoFecha(rs.getDate("fecha_nac"));
                motivo_ing.setSelectedItem(rs.getString("motivo_ing"));
                ingreso_granja.setDatoFecha(rs.getDate("ingreso_granja"));
                ingreso_sist.setDatoFecha(rs.getDate("ingreso_sist"));
                color.setText(rs.getString("color"));
                tipo_concepcion.setSelectedItem(rs.getString("tipo_concepcion"));
                tatuaje_der.setSelected(rs.getBoolean("tatuaje_izq"));
                tatuaje_izq.setSelected(rs.getBoolean("tatuaje_der"));

                modificar.setEnabled(true);
                agregar.setEnabled(false);
                idvaca.setEnabled(false);
//                id.setEnabled(false);

            } else {
//                JOptionPane.showMessageDialog(null, "El Area no existe");
                WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
                wa.titulo.setText("¡¡VACA NO REGISTRADA!!");
                wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
                wa.setVisible(true);

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pnlpotrero.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(pnlpotrero.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(pnlpotrero.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(pnlpotrero.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buscarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed

        if (idvaca.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Complete el espacio vacio!!");
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("FALTÓ EL NOMBRE DE LA VACA");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);
            //            modificar.setEnabled(false);        
        } else if (nombre_vaca.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Complete el espacio vacio!!");
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("FALTÓ EL NOMBRE DE LA VACA");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);
            //            modificar.setEnabled(false);        
        } else if (no_siniga.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("FALTÓ EL NÚMERO DE SINIGAN");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (no_registro.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("FALTÓ EL NUMERO DE REGISTRO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (raza_id_raza.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("FALTÓ LA RAZA DE LA VACA");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (potrero_idpotrero.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("FALTÓ EL POTRERO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (motivo_ing.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("FALTÓ EL MOTIVO DE INGRESO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (tipo_concepcion.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("FALTÓ EL TIPO DE CONCEPCIÓN");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (color.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("FALTÓ EL COLOR DE LA VACA ");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);
        } else {
            try {
                Controlador.Conexion con = new Controlador.Conexion();
                con.ConexionPostgres();
                //JOptionPane.showMessageDialog(null, "El Area está repetida");
                Boolean der = tatuaje_der.isSelected();
                Boolean izq = tatuaje_izq.isSelected();
                con.actualizar("insert into vaca (idvaca,potrero_idpotrero,"
                        + "raza_id_raza,no_siniga,nombre_vaca,"
                        + "no_registro,fecha_nac,motivo_ing,ingreso_granja,"
                        + "ingreso_sist,color,tipo_concepcion,tatuaje_der,tatuaje_izq"
                        + ") values('" + idvaca.getText()
                        + "', '" + obteneriddelpotrero(potrero_idpotrero)
                        + "'," + obteneriddelaraza(raza_id_raza)
                        + "," + no_siniga.getText()
                        + ",'" + nombre_vaca.getText()
                        + "','" + no_registro.getText()
                        + "','" + fecha_nac.getDatoFecha()
                        + "','" + motivo_ing.getSelectedItem().toString()
                        + "','" + ingreso_granja.getDatoFecha()
                        + "','" + ingreso_sist.getDatoFecha()
                        + "','" + color.getText()
                        + "','" + tipo_concepcion.getSelectedItem().toString()
                        + "','" + der
                        + "','" + izq + "')");
                //                    JOptionPane.showMessageDialog(null, "Area Registrada");
                SuccessAlert sa = new SuccessAlert(new principal.Principal123(), true);
                sa.titulo.setText("VACA REGISTRADA!");
                sa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
                sa.titulo.setForeground(new java.awt.Color(153, 153, 153));
                sa.setVisible(true);

                idvaca.setText("");
                potrero_idpotrero.setSelectedIndex(0);
                raza_id_raza.setSelectedIndex(0);
                no_siniga.setText("");
                nombre_vaca.setText("");
                no_registro.setText("");
                fecha_nac.setDatoFecha(null);
                ingreso_granja.setDatoFecha(null);
                ingreso_sist.setDatoFecha(null);
                color.setText("");
                tipo_concepcion.setSelectedIndex(0);
                tatuaje_der.setSelected(false);
                tatuaje_izq.setSelected(false);
                con.cerrar();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_agregarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        if (idvaca.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Complete el espacio vacio!!");
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL ID DE VACA");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);
            //            modificar.setEnabled(false);        
        } else if (nombre_vaca.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Complete el espacio vacio!!");
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL NOMBRE DE LA VACA");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);
            //            modificar.setEnabled(false);        
        } else if (no_siniga.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL NUMERO SINIGAN");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (no_registro.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL NUMERO DE REGISTRO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (raza_id_raza.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, ESCOJA LA RAZA");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (potrero_idpotrero.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, ESCOJA EL POTRERO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (color.getText().isEmpty()) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, DIGITE EL COLOR DE LA VACA");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (motivo_ing.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, ESCOJA EL MOTIVO DE INGRESO");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else if (tipo_concepcion.getSelectedIndex() == 0) {
            WarningAlertCerrar wa = new WarningAlertCerrar(new principal.Principal123(), true);
            wa.titulo.setText("POR FAVOR, ESCOJA EL TIPO DE CONCEPCIÓN");
            wa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            wa.titulo.setForeground(new java.awt.Color(153, 153, 153));
            wa.setVisible(true);

        } else {

            modificar.setEnabled(false);

            try {
                Conexion con = new Conexion();
                con.ConexionPostgres();

                String sql = ("Update vaca set potrero_idpotrero  = '"
                        + obteneriddelpotrero(potrero_idpotrero)
                        + "', raza_id_raza = '" + obteneriddelaraza(raza_id_raza)
                        + "', no_siniga = " + no_siniga.getText()
                        + ", nombre_vaca = '" + nombre_vaca.getText()
                        + "', no_registro = '" + no_registro.getText()
                        + "', fecha_nac = '" + fecha_nac.getDatoFecha()
                        + "', motivo_ing = '" + motivo_ing.getSelectedItem().toString()
                        + "', ingreso_granja = '" + ingreso_granja.getDatoFecha()
                        + "', ingreso_sist = '" + ingreso_sist.getDatoFecha()
                        + "', color = '" + color.getText()
                        + "', tipo_concepcion = '" + tipo_concepcion.getSelectedItem().toString()
                        + "', tatuaje_der = '" + tatuaje_der.getText()
                        + "', tatuaje_izq = '" + tatuaje_izq.getText()
                        + "' where idvaca = '" + idvaca.getText() + "'");
                System.out.print(sql);
                con.actualizar(sql);
//                JOptionPane.showMessageDialog(null, "INFORMACION MODIFICADA!");
                SuccessAlert sa = new SuccessAlert(new principal.Principal123(), true);
                sa.titulo.setText("VACA MODIFICADO");
                sa.titulo.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
                sa.titulo.setForeground(new java.awt.Color(153, 153, 153));
                sa.setVisible(true);

                idvaca.setText("");
                nombre_vaca.setText("");
                no_registro.setText("");
                no_siniga.setText("");
                color.setText("");
                motivo_ing.setSelectedIndex(0);
                tipo_concepcion.setSelectedIndex(0);
                tatuaje_der.setSelected(false);
                tatuaje_izq.setSelected(false);
                potrero_idpotrero.setSelectedIndex(0);
                raza_id_raza.setSelectedIndex(0);
                fecha_nac.setDatoFecha(null);
                ingreso_granja.setDatoFecha(null);
                ingreso_sist.setDatoFecha(null);

                tatuaje_der.setSelected(false);
                tatuaje_izq.setSelected(false);
                con.cerrar();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(pnlpotrero.class.getName()).log(Level.SEVERE, null, ex);
            }

            modificar.setEnabled(false);
//            cedula.setEnabled(true);
            agregar.setEnabled(true);
            idvaca.setEnabled(true);
        }


    }//GEN-LAST:event_modificarActionPerformed

    private void tatuaje_derActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tatuaje_derActionPerformed
        //        tatuaje_der.setSelected(true);
        //        tatuaje_izq.setSelected(false);

        if (tatuaje_der.isSelected() == true) {
            String opcionsexo = "Derecho";
            tatuaje_izq.setSelected(false);

        } else {
            tatuaje_izq.setSelected(true);
            String opcionsexo = "Izquierdo";
            tatuaje_der.setSelected(false);
        }
    }//GEN-LAST:event_tatuaje_derActionPerformed

    private void tatuaje_izqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tatuaje_izqActionPerformed

        if (tatuaje_izq.isSelected() == true) {
            String opcionsexo = "Izquierdo";
            tatuaje_der.setSelected(false);
        } else {
            tatuaje_der.setSelected(true);
            String opcionsexo = "Derecho";
            tatuaje_izq.setSelected(false);
        }
    }//GEN-LAST:event_tatuaje_izqActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        idvaca.setText("");
        potrero_idpotrero.setSelectedIndex(0);
        raza_id_raza.setSelectedIndex(0);
        no_siniga.setText("");
        nombre_vaca.setText("");
        no_registro.setText("");
        fecha_nac.setDatoFecha(null);
        ingreso_granja.setDatoFecha(null);
        ingreso_sist.setDatoFecha(null);
        color.setText("");
        tipo_concepcion.setSelectedIndex(0);
        tatuaje_der.setSelected(false);
        tatuaje_izq.setSelected(false);

    }//GEN-LAST:event_limpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField color;
    private rojeru_san.componentes.RSDateChooser fecha_nac;
    private javax.swing.JTextField idvaca;
    private rojeru_san.componentes.RSDateChooser ingreso_granja;
    private rojeru_san.componentes.RSDateChooser ingreso_sist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton modificar;
    private javax.swing.JComboBox motivo_ing;
    private javax.swing.JTextField no_registro;
    private javax.swing.JTextField no_siniga;
    private javax.swing.JTextField nombre_vaca;
    private static javax.swing.JComboBox potrero_idpotrero;
    public static javax.swing.JComboBox raza_id_raza;
    private javax.swing.JRadioButton tatuaje_der;
    private javax.swing.JRadioButton tatuaje_izq;
    public static componentes.org1.bolivia.combo.SComboBox tipo;
    private javax.swing.JComboBox tipo_concepcion;
    // End of variables declaration//GEN-END:variables
}
